### PR TITLE
Upgrade to `gradle-build-action@v2`

### PR DESCRIPTION
**Pull request by bigdaz**
This PR upgrades the GitHub actions workflow to the latest v2 version (presently v2.0-beta.7). This new action has simpler configuration and does a better job of caching the Gradle User Home state between build invocations.

The build-cache was also enabled for the build, since the action will now persist the local build cache between workflow invocations.

### CODE REVIEW

**Comment by tbroyer** [comment]
It's a pity that:
* it doesn't take lockfiles into account (or verification metadata)
* it doesn't cache distributions independently from one another

With my current setup, distributions should be properly cached and reused (had I used the same cache key as the gradle-build-action, they would even have been cached when switching from 6.9 to 7.2 for the build while the test matrix switched from 7.2 to 6.9), whereas with v2 each TestKit in the matrix would have its own cache key with both distributions, consuming excessive space (caching is not only about speed, but also ecological impact)
And dependencies are cached based on the lockfiles (currently, this means that whenever I change a single dependency then all dependencies are downloaded again without reuse, but on the other end the cache only contains the dependencies actually used by the build, and no single leftover from a previous build).
I understand that this would be different for each build setup, but in this specific case I don't think the new behavior is an improvement.

**Comment by bigdaz** [comment]
Thanks for the feedback @tbroyer. I'm not sure if your reply is based on actual experience,  or is based on assumptions with the way the new action is implemented. 

I will do some experimentation in my fork to see, but my first impressions were that the new action performed more efficiently, both in terms of speed _and_ in terms of cache storage use.

**Comment by bigdaz** [comment]
I will need to investigate how to integrate lockfiles into the caching mechanism. I can see why you like your current setup, however there is an impact that you may not be aware of: only the first job to run with a particular set of lockfiles will cache its dependencies. This is because GitHub cache entries cannot be overwritten.

In your example, this means that the `linux` job will save the dependencies for the current lockfiles, and each of the `test*` jobs will start with these dependencies, downloading any additional deps every time.

**Comment by bigdaz** [comment]
Apologies for the subsequent commits on this PR. I will submit a new PR on a branch that won't be polluted by my fork experiements.

Please feel free to continue commenting on this PR.

**Comment by bigdaz** [comment]
@tbroyer Here's some results that you might interesting. They give a better picture of how the caching works in practise.
Putting this together was useful for me to gauge the effectiveness of the caching, too :).

I ran the workflow twice, using a custom cache-key-prefix that effectively starts with an empty cache.

- First `linux` job:
  - Starts with an [empty Gradle User Home](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979516353?check_suite_focus=true#step:4:32)
  - Finishes with [958Mb Gradle User Home](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979516353?check_suite_focus=true#step:9:68)
  - Artifact bundles are then extracted and cached based on identity:
      - [Wrapper zips 103Mb](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979516353?check_suite_focus=true#step:9:86)
      - [Dependency jars 229Mb](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979516353?check_suite_focus=true#step:9:92)
      - generated-gradle-jars, kotlin-dsl, instrumented-jars also extracted
  - Remaining [`.gradle/caches` directory is stored 1Mb](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979516353?check_suite_focus=true#step:9:125)
- First `Gradle 7.1.1` job
  - Starts with [Gradle User Home cached from `linux`](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979564295?check_suite_focus=true#step:4:85)
  - Extracts new [wrapper-zips bundle that contains 6.9 and 7.1.1](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979564295?check_suite_focus=true#step:9:85)
  - Does not need to cache dependencies (or other bundles) since they are unchanged
  - Saves the remaining `caches` directory [1Mb](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979564295?check_suite_focus=true#step:9:122)
- Second `linux` job:
   - Restores [GUH from first `linux` execution](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979624391?check_suite_focus=true#step:4:83)
   - Post execution, all artifact bundles are unchanged, so only stores remaining `.gradle/caches` directory [1Mb](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979624391?check_suite_focus=true#step:9:108)
- Second `Gradle 7.1.1` job:
   - Restores state from previous `gradle 7.1.1` job. The job is encoded in [`test-gradle[2ef75f2f9f0656f606441ab078ef76a4]` part of the cache key.](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979630435?check_suite_focus=true#step:4:27)
   - Again, all artifact bundles are up-to-date and only the remaining `caches` dir is stored [1Mb](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979630435?check_suite_focus=true#step:9:110)

Some issues:
1. I cherry-picked '7.1.1', since the '7.2' job actually took ran after the '5.5.1' job finished and started with that cache entry. This results in 7.2 having an [extraneous wrapper zip in its bundle](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979630435?check_suite_focus=true#step:9:110).
2. On a similar note: https://github.com/gradle/gradle-build-action/issues/78
3. Artifact bundles are currently all-or-nothing, which means if a build downloads a single additional dependency, a new zip containing _all_ of the dependencies will be cached. Ideally we'd use some sort of layered cache to avoid this.
4. Cache entries will grow forever, unless the Gradle cache cleanup mechanism can kick in. I'd like to enhance Gradle so that cache cleanup could be triggered to remove any files that were not actually used during the job execution.

**Comment by tbroyer** [comment]
> Thanks for the feedback @tbroyer. I'm not sure if your reply is based on actual experience, or is based on assumptions with the way the new action is implemented.

I actually read the action's source code (I looked at the `main` branch though, not `releases/v2`).

> I will need to investigate how to integrate lockfiles into the caching mechanism. I can see why you like your current setup, however there is an impact that you may not be aware of: only the first job to run with a particular set of lockfiles will cache its dependencies. This is because GitHub cache entries cannot be overwritten.
> 
> In your example, this means that the `linux` job will save the dependencies for the current lockfiles, and each of the `test*` jobs will start with these dependencies, downloading any additional deps every time.

Yes, but I'm thoughtful about my workflow setup, and I made sure that the first run won't download a subset of the dependencies needed by the following runs (if I had setup my workflow that way, I would have taken it into account and made a subsequent cache entry with the additional dependencies ; but that would have been suboptimal as it would have been a superset of the first one, not a layered cache entry). I also know (until proven otherwise) that the dependencies don't have OS or JVM-based variants (I suppose that using dependency verification would make sure it's the case then as it works at artifact level rather than component level?)
And actually, now that I look at it in more details, because in v1 the arguments are used in the dependencies cache key, and I use `dependencies-cache-exact` to avoid the cache entries growing forever, only the `linux` and `windows` jobs would share the cache, and other jobs will have their own.

I feel like there's no one-size-fits-all and trying to make an action behave great in all/most cases won't be possible. For people who actually care about caching (like me), having levers and knobs would be way better (like in v1 actually). That's not to say that the default behavior couldn't be improved though (including the arguments in the cache key in v1 was a good idea as a default behavior, but it would have been better if it had been configurable so I could disable it as I know it's actually bad for me).
(see, I even [make sure](https://github.com/tbroyer/gradle-errorprone-plugin/blob/99a7472f6c15fa6cc9000d23174938eb5ef94300/.github/workflows/gradle.yaml#L113) I'm not downloading JDK 11 as I know it's [preinstalled](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java))

> Some issues:
> 
> 1. I cherry-picked '7.1.1', since the '7.2' job actually took ran after the '5.5.1' job finished and started with that cache entry. This results in 7.2 having an [extraneous wrapper zip in its bundle](https://github.com/bigdaz/gradle-errorprone-plugin/runs/3979630435?check_suite_focus=true#step:9:110).
> 2. On a similar note: [Suboptimal caching for wrapper dists and generated-gradle-jars gradle/gradle-build-action#78](https://github.com/gradle/gradle-build-action/issues/78)

Yes, this is rather bad.
BTW, I thought generated-gradle-jars didn't involve downloading anything, so do they really warrant being cached? (it's a trade-off between storage+network and CPU, and I don't have the numbers to tell whether caching is worth saving those CPU cycles)

> 3. Artifact bundles are currently all-or-nothing, which means if a build downloads a single additional dependency, a new zip containing _all_ of the dependencies will be cached. Ideally we'd use some sort of layered cache to avoid this.
> 4. Cache entries will grow forever, unless the Gradle cache cleanup mechanism can kick in. I'd like to enhance Gradle so that cache cleanup could be triggered to remove any files that were not actually used during the job execution.

For that last item, this is why I use `dependencies-cache-exact` at the expense of starting from scratch when I update a dependency. As a possible solution, how about moving the restored dependencies to a different location and use it as a read-only dependency cache (https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:shared-readonly-cache); that way the new build will pick artifacts from this cache before going to the network: if all dependencies are reused, it'll have just moved files around (this could be optimized by not using that read only cache if that situation can be detected upfront), and otherwise the new dependency cache only includes the dependencies actually used by the build yet leveraging a file-system cache and not re-downloading anything (only downloading new dependencies).
(btw, does TestKit uses the Gradle User Home as a read-only dependency cache to avoid reaching the network? and/or can it be configured to do just that? without configuring the TestKit Gradle User Home to the same directory, which would make it inherit init scripts too)

**Comment by bigdaz** [comment]
Thanks @tbroyer for your input. I suspect you might be in the minority of users who put a lot of thought into caching and how to optimize their workflows. My implicit goal with `v2` was to develop something that provided the best performance optimization out of the box with minimal configuration for the majority of users. 

> I'm thoughtful about my workflow setup, and I made sure that the first run won't download a subset of the dependencies needed by the following runs

I've seen many examples of workflows that are just the opposite, like running a simple `classes` invocation in the first job, which then populates the cache with a small set of dependencies and then requires all subsequent jobs to re-download the additional dependencies each time.

> I feel like there's no one-size-fits-all and trying to make an action behave great in all/most cases won't be possible.

I hope you're wrong on this, and that we can build an action that works great for _most_ cases with minimal configuration. I guess we'll see :). Hopefully this approach won't be incompatible with power-users like yourself, by providing the necessary hooks and configuration options. But that's certainly not been my focus when developing `v2`.

> BTW, I thought generated-gradle-jars didn't involve downloading anything, so do they really warrant being cached? (it's a trade-off between storage+network and CPU, and I don't have the numbers to tell whether caching is worth saving those CPU cycles)

You're correct: `v2` is not focussed on only caching things that are downloaded. My experience is that on a clean agent it's often recompiling the build scripts and creating `generated-gradle-jars` is more expensive, time-wise, than downloading dependencies.
For example, [this build](https://github.com/tbroyer/gradle-errorprone-plugin/runs/3394325949?check_suite_focus=true#step:4:93) appears to have [downloaded all dependencies](https://scans.gradle.com/s/z2gfcefu42phg/performance/network-activity), [adding 2.2s](https://scans.gradle.com/s/z2gfcefu42phg/performance/dependency-resolution) to total build time (downloads happen during task execution, in parallel). On the other hand, [configuration time for the build was > 1min](https://scans.gradle.com/s/z2gfcefu42phg/performance/configuration), including script compilation and generating the gradle-api jars.

By contrast, my fork running with `gradle-build-action@v2` has [configuration time of around 6s](https://scans.gradle.com/s/y45v5l55u3e3u/performance/configuration), primarily due to the caching of compiled scripts and generated-gradle-jars.

So I guess it depends if your goal is to reduce downloads, or to make the build complete sooner. I am assuming the latter, but there could be a good reason for the former.

> As a possible solution, how about moving the restored dependencies to a different location and use it as a read-only dependency cache

This is a really interesting idea. However the way it's currently implemented Gradle will not copy files out of the shared dependency cache, but will use them in-place. So this would help when building a layered cache, but not to eliminate unused artifacts. However, if we put them in the `.m2/repo`, then Gradle _will_ copy the files into it's own cache, after performing an HTTP HEAD request to check they are valid. I'll add this to the list of ideas.

Regarding TestKit, there are plans to make this work better with `gradle-build-action` (eg https://github.com/gradle/gradle-build-action/issues/73). The idea of using the main Gradle User Home as a read-only dependency cache is quite compelling, although this would require a change in Gradle, I presume.

**Comment by tbroyer** [comment]
> Thanks @tbroyer for your input. I suspect you might be in the minority of users who put a lot of thought into caching and how to optimize their workflows. […] I've seen many examples of workflows that are just the opposite, like running a simple `classes` invocation in the first job, which then populates the cache with a small set of dependencies and then requires all subsequent jobs to re-download the additional dependencies each time.

That, sadly, doesn't really surprise me.

> > I feel like there's no one-size-fits-all and trying to make an action behave great in all/most cases won't be possible.
> 
> I hope you're wrong on this, and that we can build an action that works great for _most_ cases with minimal configuration. I guess we'll see :). Hopefully this approach won't be incompatible with power-users like yourself, by providing the necessary hooks and configuration options.

Yes, things can be made to work for everyone with the appropriate configuration options. I think the issue here is to have something that will work "as best as possible" for those lenient people who don't really care (where you have to use an approach like in v2 that stores things under keys that are a checksum of the saved files –kind of a recursive definition– and then store those cache keys in a file that's itself cached under some unique key, restored using fallback restore keys) vs some more specifically designed caches for "power users" that want to opt-in (e.g. cache dependencies based on lockfiles and possibly gradle arguments, maybe cache each generated-gradle-jar separately –automatically cache gradle-kotlin-dsl-extensions-<version>.jar if there are *.gradle.kts files, but with gradle-api and gradle-test-kit as an opt-in–, etc.)

If I had to design the cache keys, from my understanding of Gradle, I would have something like:
* `$GRADLE_USER_HOME/wrapper/<wrapper>/*/<wrapper>.zip` (each distribution cached independently, with a configuration option to tell which one to restore/cache, with `wrapper` as a special value like in v1); possibly put `$GRADLE_USER_HOME/notifications/<version>/` in there too if `<wrapper>` is of the form `gradle-<version>-{bin,all}` (this might not work for custom distributions though, so make it fully configurable), as a rule I think the fewer cache entries the better, so putting the notifications in there would be best. Maybe include the gradle-kotlin-dsl-extension-<version>.jar in the same cache entry too (including `kotlin` as a token in the cache key, so when switching to the Kotlin DSL one could restore a previous cache entry without that JAR, and then create a new entry with the JAR; the old entry will be garbage-collected after a while and a build will only use one or the other)
* `$GRADLE_USER_HOME/caches/generated-gradle-jars/<version>/gradle-api-<version>.jar`
* `$GRADLE_USER_HOME/caches/generated-gradle-jars/<version>/gradle-test-kit-<version>.jar`; or maybe include those two JARS as an opt-in in the "distribution cache", same as gradle-kotlin-dsl-extensions. If one develops a plugin (including those in buildSrc or an included build), then they can opt-in to those additional JARs (will be reflected in the cache key for proper fallback for restore keys, see above; particularly in my case here when switching from "building with 6.9.1 and testing with 7.2 through TestKit" to "building with 7.2 and testing with 6.9.1 through TestKit" for example); it would require resolving the `gradleApi()` and `gradleTestKit()` dependencies though, so it's hard to enable it automatically, and some projects would benefit from having those JARs into their own cache entries, as a "layer" above the distribution
* `$ĜRADLE_USER_HOME/caches/modules-*/files-*/` keyed with lockfiles and/or verification metadata (this would mandate the use of at least one or the other) and gradle arguments (possibly configurable to strip out e.g. project properties that are known not to influence dependency resolution)
* `$GRADLE_USER_HOME/caches/<version>/kotlin-dsl/*/*/` keyed by a checksum of all the `*.kts` and possibly the lockfiles and/or verification metadata (and of course the version of Gradle being used)
* etc.

That said, I don't know what are those JARs you call "instrumented JARs" in v2 (are those the results of artifact transforms? if they're, then cache them keyed by the dependencies' key and a hash of the build scripts), and I don't know much about how/where build cache and configuration cache are stored.

But basically you get the idea: anything that can be determined by looking at the input files (gradle-wrapper.properties, lockfiles, verification metadata, arguments, build scripts, etc.) or possibly helped with explicit configuration (e.g. Gradle version if it cannot be determined from the wrapper/distribution name/URL, overridden arguments for the cache key, or opt-ins for some features) should be keyed to those inputs, independently of the GitHub commit or whatever.

That would be my approach, but that's not necessarily the best :man_shrugging: 
And as I said, it cannot really be used as the default for projects that don't really care and/or do want a turn-key solution, and different projects might have conflicting needs (cf. gradle-api and gradle-test-kit above, merged with the distribution or cached separately).

> But that's certainly not been my focus when developing `v2`.

:+1: 

> > BTW, I thought generated-gradle-jars didn't involve downloading anything, so do they really warrant being cached? (it's a trade-off between storage+network and CPU, and I don't have the numbers to tell whether caching is worth saving those CPU cycles)
> 
> You're correct: `v2` is not focussed on only caching things that are downloaded. My experience is that on a clean agent it's often recompiling the build scripts and creating `generated-gradle-jars` is more expensive, time-wise, than downloading dependencies. For example, [this build](https://github.com/tbroyer/gradle-errorprone-plugin/runs/3394325949?check_suite_focus=true#step:4:93) appears to have [downloaded all dependencies](https://scans.gradle.com/s/z2gfcefu42phg/performance/network-activity), [adding 2.2s](https://scans.gradle.com/s/z2gfcefu42phg/performance/dependency-resolution) to total build time (downloads happen during task execution, in parallel). On the other hand, [configuration time for the build was > 1min](https://scans.gradle.com/s/z2gfcefu42phg/performance/configuration), including script compilation and generating the gradle-api jars.
> 
> By contrast, my fork running with `gradle-build-action@v2` has [configuration time of around 6s](https://scans.gradle.com/s/y45v5l55u3e3u/performance/configuration), primarily due to the caching of compiled scripts and generated-gradle-jars.
> 
> So I guess it depends if your goal is to reduce downloads, or to make the build complete sooner. I am assuming the latter, but there could be a good reason for the former.

OK, I'm sold :wink: 
(in this case, while the gradle-api JAR is quite big, because it doesn't change very often –well, in this specific project that doesn't have many updates, this is not really the case–, I think it's worth caching it as the cost of caching will be amortized; it's always a trade-off)

> > As a possible solution, how about moving the restored dependencies to a different location and use it as a read-only dependency cache
[…]
> Regarding TestKit, there are plans to make this work better with `gradle-build-action` (eg [gradle/gradle-build-action#73](https://github.com/gradle/gradle-build-action/issues/73)). The idea of using the main Gradle User Home as a read-only dependency cache is quite compelling, although this would require a change in Gradle, I presume.

Should I file an issue on the Gradle repo to improve TestKit with this?

**Comment by tbroyer** [comment]
> where you have to use an approach like in v2 that stores things under keys that are a checksum of the saved files –kind of a recursive definition– and then store those cache keys in a file that's itself cached under some unique key, restored using fallback restore keys

Ah, looks like I misunderstood/misremembered how it actually works. IIUC, each "cache" always includes the commit sha1 and thus will almost always be restored using "fallback matching".

> That would be my approach, but that's not necessarily the best 
> And as I said, it cannot really be used as the default for projects that don't really care and/or do want a turn-key solution, and different projects might have conflicting needs (cf. gradle-api and gradle-test-kit above, merged with the distribution or cached separately).

Oh, it might be possible to have the best of both worlds actually: have everything configurable for power users, and a "discover" mode enabled by default for a turn-key solution, where the "discover" mode would actually look at what files are there after the build, generate a corresponding configuration, and store that configuration keyed by the commit sha1. For dependencies that could mean storing the generated cache key for instance (or not storing anything, and rely on fallbacks like you do in v2 today), but for distributions it could just store the versions (and/or default to using `wrapper` like in v1). This would still lead to an ever-growing cache (until you somehow use the Gradle cleanup algorithm) but none different to the one generated today in v1 without exact cache-key matching, or the one from actions/setup-java@v2.
Discover mode could possibly be enabled/disabled selectively for each kind of cache (distributions: discover | array of versions with special values like wrapper, release-candidate, nightly or latest; dependencies: discover | lockfiles | verification-metadata | some cache key, e.g. generated through hashFiles; same could be added later for Java toolchains, etc.); as soon as one uses discover mode, then the action could restore the previous configuration and then restore caches pointed to by the configuration.

**Comment by bigdaz** [comment]
Thanks for your continued feedback.

Last night I came up with the same idea as you for different "bundles" of artifacts (like downloaded dependencies) that should remain relatively consistent over time.
1. By default use a "discovered" cache key based on the actual artifacts within Gradle User Home. This is basically stating that we don't know what source/workflow values can cause these to change.
2. Allow users to override this by providing a specific cache key for a particular bundle. In your case, you'd provide a key based on the dependency lock files.
3. Where possible, extend the action to detect cases where the cache key can be known up-front and doesn't need to be discovered.

This should allow things to mostly work out of the box, but allow caching to be optimized when users _know_ a precise way to determine the cache key.

This scenario would make also it possible to:
1. Restore certain artifact bundles even if the Gradle User Home cache entry wasn't found.
2. If the Gradle User Home is restored _and_ no entry is found for the user-provided bundle key, we could still restore the previous bundle entry. This way if you add a single dependency we could start with the previous set, and only add what's missing.

I'm treating ever-growing cache entries as a separate topic. The information already exists which files were actually used since a particular timestamp, and I think we should be able to find a way to cleanup all unused files before caching.

**Comment by bigdaz** [comment]
I've raised https://github.com/gradle/gradle-build-action/issues/103 for allowing users to specify precise cache keys.

**Pull request closed without merging**
